### ISSUE TITLE
Tab autocomplete for goat aliases

### ISSUE THREAD

**Issue by Joald** [0mp/goat#42]
My shell doesn't do tab autocomplete for aliases created by goat, that would be nice to have.

**Comment by 0mp** [comment]
@Joald what shell do you use?

**Comment by Joald** [comment]
Bash.

**Comment by 0mp** [comment]
Goat installs its completions into ~/.bash_completion.d at the moment. You just have to source it.

Here's the way I'm doing it: the bash-completion library sources a couple of files and directories in order to load all the completions for you. One of those files, which could be edited by a user without root privileges is `~/.bash_completion`. Here's what I put in mine `~/.bash_completion`: https://github.com/0mp/dotfiles/blob/master/bash/bash_completion

**Comment by Joald** [comment]
That works, thanks!

**Comment by 0mp** [comment]
@Joald Cheers!

I'm slowly working on rewriting the build system and packaging goat for the FreeBSD ports. The manual page is on its way as well. Hopefully, the whole process is going to be automated soon.
